data_root_dir: /export/scratch/ialgroup
run_dir: /export/data/mickler/fairchem_models
account: ocp
qos: ocp
mode: LOCAL
device: CUDA
ranks_per_node: 1
dataloader_workers: 0
debug: True
mem_gb: 0
cpus_per_task: 8
